version = 1

test_patterns = [
  '_test.go'
]

exclude_patterns = [
  'bin/'
]

[[analyzers]]
name = 'go'
enabled = true


  [analyzers.meta]
  import_path = 'https://github.com/donmstewart/porter-kustomize'
