# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - rm -Rf dist/
    - dep ensure
    - go generate ./...
dist: dist/mixins
builds:
  # You can have multiple builds defined as a yaml list
  - # ID of the build.
    # Defaults to the project name.
    id: "build-runtime"

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: porter-kustomize-runtime

    # Path to main.go file or main package.
    # Default is `.`.
    main: ./cmd/kustomize/.

    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -w -X github.com/donmstewart/porter-mixin/pkg.Version={{.Version}} -X github.com/donmstewart/porter-mixin/pkg.Commit={{.Tag}}
      -
    env:
      - CGO_ENABLED=0

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - darwin
      - linux
      - windows

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64.
    goarch:
      - amd64

  - # ID of the build.
    # Defaults to the project name.
    id: "build-client"

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: porter-kustomize

    # Path to main.go file or main package.
    # Default is `.`.
    main: ./cmd/kustomize/.
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -w -X github.com/donmstewart/porter-mixin/pkg.Version={{.Version}} -X github.com/donmstewart/porter-mixin/pkg.Commit={{.Tag}}
    env:
      - CGO_ENABLED=0
      - CLIENT_TARGET="dist/mixins/kustomize/{{.Version}}/kustomize-{{.Env.GOOS}}-{{.Env.GOARCH}}"
    goos:
      - "{{.Env.GOOS}}"
    goarch:
      - "{{.Env.GOARCH}}"
    #hooks:
    #  post:
    #    install "{{.Env.CLIENT_TARGET}}"
archives:
  - # ID of this archive.
    # Defaults to `default`.
    id: porter-kustomize

    # Builds reference which build instances should be archived in this archive.
    builds:
    - default
    # Archive name template.
    # Defaults:
    # - if format is `tar.gz`, `gz` or `zip`:
    #   - `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
    # - if format is `binary`:
    #   - `{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
