# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - rm -Rf dist/
    #- dep ensure
    - go generate ./...
builds:
    # You can have multiple builds defined as a yaml list
    -
      # ID of the build.
      # Defaults to the project name.
      id: "build-runtime"

      # Binary name.
      # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
      # Default is the name of the project directory.
      binary: porter-kustomize-runtime

      # Path to main.go file or main package.
      # Default is `.`.
      main: ./cmd/kustomize/.

      # Custom ldflags templates.
      # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
      ldflags:
        - -w -X github.com/donmstewart/porter-mixin/pkg.Version={{.Version}} -X github.com/donmstewart/porter-mixin/pkg.Commit={{.Tag}}
        -
      env:
        - CGO_ENABLED=0

      # GOOS list to build for.
      # For more info refer to: https://golang.org/doc/install/source#environment
      # Defaults are darwin and linux.
      goos:
        - darwin
        - linux
        - windows

      # GOARCH to build for.
      # For more info refer to: https://golang.org/doc/install/source#environment
      # Defaults are 386 and amd64.
      goarch:
        - amd64

    - # ID of the build.
      # Defaults to the project name.
      id: "build-client"

      # Binary name.
      # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
      # Default is the name of the project directory.
      binary: porter-kustomize

    # Path to main.go file or main package.
      # Default is `.`.
      main: ./cmd/kustomize/.
      # Custom ldflags templates.
      # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
      ldflags:
        - -w -X github.com/donmstewart/porter-mixin/pkg.Version={{.Version}} -X github.com/donmstewart/porter-mixin/pkg.Commit={{.Tag}}
      env:
        - CGO_ENABLED=0
      goos:
        - darwin
      goarch:
        - amd64
      hooks:
        post:
          install dist/mixins
dist: dist/mixins
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
