name: Release

on: 
  release:
    branches:
    - master
    - develop

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Set up Go
        uses: actions/setup-go@master
      -
         name: Deps
         run: |
           go get -u github.com/golang/dep/cmd/dep
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
