name: Release

on: 
  release:
    branches:
    - master
    - develop

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/donmstewart/porter-kustomize
          
      -
        name: Set up Go
        uses: actions/setup-go@master
      -
         name: Deps
         run: |
            mkdir -p $GOPATH/bin
            export PATH=$PATH:$GOPATH/bin
            if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
            fi
         env:
           GOPATH: /home/runner/work/porter-kustomize/go
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        env:
          GOPATH: /home/runner/work/porter-kustomize/go
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
