name: Release

on: 
  release:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Project
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/donmstewart/porter-kustomize
        
    - name: GitHub Create Tag Release
      uses: Roang-zero1/github-create-release-action@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'porter-kustomize-*'
